apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deploy
  labels:
    env: app
    key: version
spec:
  replicas: 0
  selector:
    matchLabels:
      env: app
      key: version
  template:
    metadata:
      labels:
        env: app
        key: version
    spec:
      containers:
        - name: service-deploy
          image: durgaprasaduniq/project:self
          ports:
            - containerPort: 8080
